### ISSUE TITLE
Extraction fails when user/group set with extract_path no permissions

### ISSUE THREAD

**Issue by fatmcgav** [voxpupuli/puppet-archive#108]
When attempting to use the `Archive` resource to extract a zip file into `/usr/local/` with a `user`/`group` value set, and `extract_path` set to a directory where the `user`/`group` doesn't have permissions, the extract fails (silently - raised as #107). 

Could possibly work-around this by `chown`ing the files after extraction, rather than trying to run the extraction as the `user`/`group`.

Related to #22.

**Comment by nanliu** [comment]
Not sure how to solve this, we can make some assumptions of the extraction target directory based on creates parameter, is that reasonable? something along the line of extract as root and recursively chmod the creates directory (but only do that as a rescue of exception?). would it be better for your use case to just use archive with root and subscribe with an chmod to the user/group you want?

**Comment by fatmcgav** [comment]
@nanliu Yeh, as it happens I went with a subscribed exec chmod... 

Though a recursive chmod on an exception might be a good alternative...

**Comment by jyaworski** [comment]
Do we actually want this functionality? I see the use-case for it. Is there a decent way to chmod/chown on Windows, or is that even a thing?

**Comment by nanliu** [comment]
This is documented in https://github.com/nanliu/puppet-archive/tree/GH-55#file-permission and will be part of #55. I think the first option (manage the extraction directory) should work better than subscribed exec, but I documented both. Please review and feel free to reopen this issue if you have any further concerns.
