### ISSUE TITLE
params gem provider logic fails with PE puppet 2015.03

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-archive#109]
Just downloaded PE 2015.03 and the params code that determines which gem provider to use is not working correctly because $::aio_agent_version does not exist. Maybe this should be a case statement comparing all the versions since PE puppet no longer contains 'puppet enterprise' in the newer versions

https://github.com/voxpupuli/puppet-archive/blob/master/manifests/params.pp#L22

similar to #106 but slightly different

**Comment by logicminds** [comment]
```puppet
if $::puppetversion =~ /Puppet Enterprise/ and $::osfamily != 'Windows' {
    $gem_provider = 'pe_gem'
  } elsif $::aio_agent_version {
    $gem_provider = 'puppet_gem'
  } else {
    if versioncmp($::puppetversion, '4.0.0') >= 0 {
      $gem_provider = 'puppet_gem'
    } else {
      $gem_provider = 'gem'
    }
  }

```
The above code seems to work for me.  I am not sure when PE puppet stoppped displaying puppet enterprise in the puppetversion though.

**Comment by xaniasd** [comment]
https://tickets.puppetlabs.com/browse/FACT-1280

**Comment by logicminds** [comment]
Also this issue was recently merged which might change some of the code above.

https://github.com/puppetlabs/puppetlabs-pe_gem/pull/10

**Comment by aerostitch** [comment]
Hi,

The latest changes brought by #117 and #121 should bring what you asked for here. Can you confirm please?
If so I think this can be closed right?

Thanks
Joseph (JH) ;)

**Comment by jyaworski** [comment]
Closing due to recently-merged PRs. Please re-open if this is still an issue.
