### ISSUE TITLE
support stripping of directories

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-archive#114]
many compression tools support stripping of a number of directories, we should too

**Comment by jyaworski** [comment]
Can you give an example?

**Comment by eljohn1014** [comment]
I am looking for this feature as well. can you add in an option to do strip-components=<num> so that we can use the --strip-components=<num> flag in tar

**Comment by nanliu** [comment]
That would be very specific to tar. Does the current extract_flags option suffice?

**Comment by igalic** [comment]
it would be nice to be able to have agnostic of the underlying archive format's support for the flag.

**Comment by jyaworski** [comment]
Would [dirname](https://github.com/puppetlabs/puppetlabs-stdlib#dirname) suffice?

**Comment by dhoppe** [comment]
I was able to solve this by using the parameter ```extract_command``` as you can see at the [kafka](https://github.com/voxpupuli/puppet-kafka/pull/50) module.

**Comment by jyaworski** [comment]
Given @dhoppe's great answer, I'm going to mark this as closed.
