### ISSUE TITLE
embed gems and install locally

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-archive#118]
Not sure if anybody else can appreciate doing this, but my current situation limits me from installing anything directly off the internet.  So to make things easier I ended up putting the gems inside the module and installing locally. 

If this kind of addition is welcomed, I'll make a PR for it. 

But it looks something like:

```puppet
  $archive::params::path               = 'C:/Windows/Temp'  # for context only
  $faraday_source            = "${archive::params::path}/faraday-0.9.1.gem"
  $faraday_middleware_source = "${archive::params::path}/faraday_middleware-0.10.0.gem"
  $multipart_post_source     = "${archive::params::path}/multipart-post-2.0.0.gem"

  file{$faraday_source:
    ensure => present,
    source => 'puppet:///modules/archive/faraday-0.9.1.gem',
    before => Package['faraday']
  }
  file{$faraday_middleware_source:
    ensure => present,
    source => 'puppet:///modules/archive/faraday_middleware-0.10.0.gem',
    before => Package['faraday_middleware']
  }
  file{$multipart_post_source:
    ensure => present,
    source => 'puppet:///modules/archive/multipart-post-2.0.0.gem',
    before => Package['multipart-post']
  }
  package{ 'multipart-post':
    ensure   => present,
    provider => $archive::params::gem_provider,
    install_options => '--local',
    source   => $multipart_post_source,
  }
  package { 'faraday':
    ensure   => present,
    provider => $archive::params::gem_provider,
    install_options => '--local',
    source   => $faraday_source,
    require  => Package['multipart-post'],
  }
  package { 'faraday_middleware':
    ensure   => present,
    provider => $archive::params::gem_provider,
    install_options => '--local',
    source   => $faraday_middleware_source,
    require  => Package['faraday'],
  }


```

**Comment by jyaworski** [comment]
Isn't this the kind of thing that packaging as RPMs solves?

**Comment by logicminds** [comment]
RPMs only work on redhat flavored linux. :(

**Comment by jyaworski** [comment]
I've used [fpm](https://github.com/jordansissel/fpm/wiki/ConvertingGems) to build Debian packages as well.

**Comment by logicminds** [comment]
Also using Windows and AIX as well.  So thats three platforms I have to build packages for, which is why I just bundled them into the module.

**Comment by jyaworski** [comment]
In that case, I'm wondering if that is out of the scope of puppet-archive and should belong in a profile.

@nanliu @daenney

**Comment by daenney** [comment]
Yeah, so no, I'm not OK with this on so many levels. For one, we'd start embedding gems in our modules which increases the module size. Worse, it puts a burden on the maintainers to ensure that these gems are kept up to date and that this behaviour works reliably across the myriad of environments this module can be used on. That's not even getting into possible security issues that we now need to watch out for for all the gems we're including.

If you can't install software of the internet, then you need to solve that problem by having an actual mirror/repository at your disposal that you can use for that purpose.

**Comment by logicminds** [comment]
I am not surprised by your comments.  Seems silly to have to resort to this kind of practice.  However, vendoring gems is common practice within the ruby community and actually preferred method for best compatibility which is really no different here.   As for the size its adds 86K to the repo. Puppet itself vendors a few gems, and in addition also vendors the entire stack with pe-agent package.  All applications written in GO embed copies of the libraries they use to make a single binary.  Puppet modules should not be treated any different.  Puppet modules should work out of the box without reliance of a gem server.  I don't see how security or maintenance would be an issue.  

Anyways, just something to think about.  Not everyone has root with or internet access to rubygems.org.

**Comment by daenney** [comment]
Puppet modules however are not Ruby gems or "the ruby community". We are the Puppet community and we've almost never resorted to bundling external dependencies this way. The packaging of Puppet itself is entirely different from the packaging of a Puppet module. One does not apply to the other.

And so we start with just 3 gems, and then it's 5, 7, 10, 36. And well, you know, that JVM, well we need that too so lets add that one too because you shouldn't have to rely on your local mirror or Oracle's download servers to get it. And while we're at it, lets add that Windows 2003 ISO image too because you should be able to set up your PXE server with an image for it without... No.

**Comment by logicminds** [comment]
This is why docker exists. Dependency hell...

**Comment by daenney** [comment]
Yes. Most places I've seen run a gem-in-a-box or similar to distribute internal gems and cache/proxy to upstream Rubygems if this is a concern for them.

**Comment by rnelson0** [comment]
This module shouldn't really care how the gems get there and whether or not you have internet access. You could put the package installation into a subclass `archive::install` and add a `$manage_gems` parameter to control whether `archive::install` is even called. Then, you could use your roles and profiles classes to load the gems however you need. Flexibility all around.

Whether this is actually needed remains a question, but it seems like a more graceful way to handle such concerns.

**Comment by daenney** [comment]
True. You could even make it so that the `package` declarations have configurable `source` entries.

**Comment by jyaworski** [comment]
I would be OK with making the package source/provider configurable. That seems to be an elegant solution.

**Comment by nanliu** [comment]
I'm removing external gem dependencies in #124, so this should no longer be an issue. Please review those changes and feel free to reopen this ticket if you have any other concerns.
