### ISSUE TITLE
$aws_cli_install defaults to true for non Amazon instances

### ISSUE THREAD

**Issue by danifr** [voxpupuli/puppet-archive#140]
getvar('::ec2_metadata') seems to return true if fact does not exist.

https://github.com/voxpupuli/puppet-archive/blob/master/manifests/params.pp#L27

**Comment by jyaworski** [comment]
Can we try changing getvar to $::?

**Comment by danifr** [comment]
This seems to work:
if getvar('::ec2_metadata') != '' and $::operatingsystem != 'Amazon' {

But I can test you suggestion too. One sec.

**Comment by danifr** [comment]
Arggg, I cannot test your change right now. I need to recreate the VM....

Anyway... I'll submit a PR with my change and we can discuss in there if we want to use your suggestion or stick with mine.

**Comment by nanliu** [comment]
The ec2_* facts only exist in aws environment so we can't use $:: alone.

**Comment by danifr** [comment]
Closing https://github.com/voxpupuli/puppet-archive/pull/141
