### ISSUE TITLE
Cannot download using wget

### ISSUE THREAD

**Issue by randradas** [voxpupuli/puppet-archive#142]
When wget is used my download fail. It seems that the server is not receiving a proper cookie header. I checked my puppet agent log and I saw this:

> Debug: Executing '/usr/bin/wget http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz -O /tmp/jdk-7u80-linux-x64.tar.gz_20160316-9551-fy9sql --max-redirect=5 --header="Cookie: "oraclelicense=accept-securebackup-cookie"'

If I run this manually in my shell, I got a wrong download. As you can see cookie header double quotes are wrong.

I tried to change **wget.rb** from this (three double quotes on Cookie):
`params += optional_switch(resource[:cookie], ['--header="Cookie: "%s"'])`

To this (two double quotes on Cookie):
`params += optional_switch(resource[:cookie], ['--header="Cookie: %s"'])`

web server is still answering like it is receiving a wrong cookie but in this case If I run the command printed by the log in my shell manually then it works.

**Comment by igalic** [comment]
@randradas would you like to provide us with a patch for this?

**Comment by randradas** [comment]
yes!, I would. I've just push it on pull requests.

**Comment by nanliu** [comment]
Odd the original spec 4c469d3 had the extra double quote, wonder how it was working originally. Is this fixed by #143?

**Comment by randradas** [comment]
as far as I know and according with wget man page, only double quotes before '--header=' and the final one are needed. https://www.gnu.org/software/wget/manual/wget.html. #143 removes this extra double quote that should not be there according with wget documentation.

**Comment by nanliu** [comment]
When I'm testing with the following resource, I only get an html page:

```puppet
archive { '/tmp/jdk-7u80-linux-x64.tar.gz':
  source   => 'http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz',
  cookie   => 'oraclelicense=accept-securebackup-cookie',
  provider => 'wget',
}
```

```bash
$ file /tmp/jdk-7u80-linux-x64.tar.gz
/tmp/jdk-7u80-linux-x64.tar.gz: HTML document text
$ head /tmp/jdk-7u80-linux-x64.tar.gz
<html>
<head>
<title>Unauthorized Request</title>
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
<link rel="stylesheet" type="text/css" href="/errors/us/assets/hp-styles.css" />
<link rel="stylesheet" type="text/css" href="/errors/us/assets/master-master.css" />

<body style="margin: 0px" bgcolor=#ffffff>
<div id="banner">
```

Do you have an working example?

**Comment by nanliu** [comment]
After some testing the following works:

```ruby
command = "wget #{params.join(' ')}"
Puppet::Util::Execution.execute(command)
```

and this does not:
```ruby
wget(params)
```

I suspect there was an extra double qoute because something with puppet metaprogrammed wget method is not handling the quotes correctly.

**Comment by randradas** [comment]
Even with extra double quote you will obtain that page, this is what lead me to find that double quote. It works with 'curl'.

So maybe receiving that web is not related with the "extra double quote" and should be managed like another issue.

**Comment by nanliu** [comment]
Ok, it's a problem with Puppet::Util::Execution.execute:

```ruby
cmd = ["wget",
 "http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz",
 "-O",
 "/tmp/jdk-7u80-linux-x64.tar.gz_20160317-16253-1m9avpd",
 "--max-redirect=5",
 "--header=\"Cookie: oraclelicense=accept-securebackup-cookie\""]
```
This fails: `Puppet::Util::Execution.execute(cmd)`, but this works `Puppet::Util::Execution.execute(cmd.join(' '))`. This is why wget(params) does not work, but my work around did. I'll put in a fix.

**Comment by jyaworski** [comment]
What puppet version? That sounds like a puppet bug.

**Comment by nanliu** [comment]
It's at least affecting PE 3.8. Hard to say what other versions since I can't just do git bisect and run spec tests. However looking at the history of puppet::util::execution, there are few recent changes. @randradas, what's your puppet version?

**Comment by randradas** [comment]
Puppet Open Source 3.8.4 in my case. Running on master and agents.
