### ISSUE TITLE
Possible issues with Windows download after 0.5.0 release

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-archive#145]
After the 0.5 release that uses pure ruby to download files, when downloading zips to a windows server I got a number of errors.

I'll see if I can reproduce on a beaker windows instance :+1:

**Comment by igalic** [comment]
uhm… what kind of errors?

**Comment by petems** [comment]
Files download ok, but are unzippable. Downloading them manually and unzipping with IE or similar works ok.

I'll see if I can get a working test case

**Comment by nanliu** [comment]
This is most likely related to #138. Please try the current master. We have another pending bug, I'll see if we can address it today and release 0.5.1

**Comment by petems** [comment]
Awesome! :smile:

**Comment by nanliu** [comment]
Release pending #149.

**Comment by nanliu** [comment]
Forge 0.5.1 released. Please reopen if #138 did not resolve this issue.
