### ISSUE TITLE
Method HTTP.follow_redirect works only with Ruby 1.9+

### ISSUE THREAD

**Issue by thiagomarinho** [voxpupuli/puppet-archive#152]
In file lib/puppet_x/bodeco/util.rb, method HTTP.follow_redirect contains this code:

```
Net::HTTP.start(uri.host, uri.port, :use_ssl => (uri.scheme == 'https')) do |http|
# ...
```

But this syntax (keyword arguments) is supported only by Ruby 2.x, right? Also, I think this option (use_ssl) doesn't exist in previous versions of the class Net::HTTP.start (as you can see here: http://ruby-doc.org/stdlib-1.8.7/libdoc/net/http/rdoc/Net/HTTP.html)

I tested without :use_ssl parameter and it worked well for me (I tested with archive::nexus, using http, and archive, using https), but I don't know if this change could impact.

**Comment by jyaworski** [comment]
@thiagomarinho we no longer 'officially' support Ruby 1.8.7. However, we do still support 1.9.3. If this only works in 2+, we should take a look.

**Comment by thiagomarinho** [comment]
@jyaworski Thanks for your answer. I can't test right now with 1.9.3 since puppet seems to not work with rvm, but I can do it later and report here. But I think that the problem also occurs with this version because keyword arguments is not available before 2.x

**Comment by jyaworski** [comment]
Tagging @nanliu

**Comment by thiagomarinho** [comment]
Hey @jyaworski , sorry for the delay. I tested with Ruby 1.9.3 and 2.0.0 and it worked with both versions. So, as archive doesn't support 1.8.7 anymore, I think that this issue can be closed, do you agree? :(

**Comment by thiagomarinho** [comment]
Maybe we could make the code compatible with 1.8.7 too, what do you think?

**Comment by bastelfreak** [comment]
:-1: I'm against adding support for 1.8.7, this is a really really old ruby version which is EOL. Please upgrade your ruby instead of adding 1.8.7 support in that module.

**Comment by igalic** [comment]
supporting 1.8 is a *lot* of work.
if you can provide a (monkey?) patch that works for people still stuck on ruby 1.8, we'll most likely merge it. and then three months down the road someone will add a feature, or fix a bug, and it will fall over again.

let me backtrack here and explain ***why*** supporting 1.8 — for us — is a lot of work:

1.8 is EOL. Has been for a long time. **none** of the development tools we use support 1.8 any more. for this reason we have banished it from travis. we don't know when 1.8 fails, and given that all the puppet version that require 1.8 have also been EOLed, we don't really care all that much.

There are older versions of archive. They are still on the forge. They still support 1.8.
They are also buggy, or less performant, or don't have the features you might need. but they support 1.8.

i'm sorry if this is answer is disatisfactory, [sometimes, floss is like that](https://mjg59.dreamwidth.org/41085.html)

**Comment by jyaworski** [comment]
@thiagomarinho some of us do still use 1.8.7 in production (raises hand) but we need to balance out use of our time; I'm more than reasonably confident that the majority of people using this module are on 1.9.3 or newer, so that's where we're focusing our time.

I would suggest an older version of archive (0.4.x should work) in the interim. There has been some testing of making puppet use newer versions of ruby on older operating systems. @bastelfreak has some experience with that.

**Comment by rnelson0** [comment]
I think we are all in agreement that Ruby 1.8.7 is not supported, and @thiagomarinho agrees it can be closed out, so I'll make that so.

**Comment by thiagomarinho** [comment]
Hey guys, thank you for all the answers. :) I understand the cost to support Ruby 1.8 would bring and despite I found just this problem when tried to run puppet in my VM, nothing guarantees that there are no other. Since the problem I was trying to resolve is the need of install faraday and faraday_middleware gems, I'll try to use a recent version of Ruby
