### ISSUE TITLE
 v0.5.1 - not catching 404 errors

### ISSUE THREAD

**Issue by bxm** [voxpupuli/puppet-archive#153]
When deploying an archive from an invalid URL, the 404 is not being caught.
Here is some (slightly simplified) code that demonstrates the problem (with an intentionally invalid URL):
```
   $digest_string = undef
   if $digest_string {
     $checksum_verify = true
     $checksum = $digest_string
   } else {
     $checksum_verify = false
     $checksum = undef
   }

    archive { 'something':
      source          => 'http://nexus:8082/xxxnexus/service/local/repositories/thirdparty/content/com/jenkins/plugins/simple-theme-plugin/0.3/simple-theme-plugin-0.3.hpi',
      path            => "/tmp/plugin.hpi",
      checksum_type   => 'sha1',
      checksum        => $checksum,
      checksum_verify => $checksum_verify,
      cleanup         => false,
      extract         => false,
    }
```
As you can see Puppet doesn't seem to mind the 404:
```
Info: Applying configuration version '1460371486'
Notice: /Stage[main]/Profile_base/Archive[something]/ensure: download archive from http://nexus:8082/xxxnexus/service/local/repositories/thirdparty/content/com/jenkins/plugins/simple-theme-plugin/0.3/simple-theme-plugin-0.3.hpi to /tmp/plugin.hpi  without cleanup
Notice: Finished catalog run in 16.73 seconds
```
This results in the 404 error text being written to `/tmp/plugin.hpi`

**Comment by nanliu** [comment]
From what I remember the ruby provider handle this correctly. I'm guessing this is an issue with the curl provider because curl command appear to be missing -f flag: https://github.com/voxpupuli/puppet-archive/blob/master/lib/puppet/provider/archive/curl.rb#L6-L13. curl consider 404 ok unless you specify curl -f.
