### ISSUE TITLE
Shellwords dependency

### ISSUE THREAD

**Issue by xaniasd** [voxpupuli/puppet-archive#161]
Using the latest version of the module gives the following error:
```Could not evaluate: uninitialized constant PuppetX::Bodeco::Archive::Shellwords```

probably related to 1819a171690d071052dd6b7264064cf30714389f

**Comment by jyaworski** [comment]
@xaniasd are you using jruby anywhere? It looks like we need to add 'require shellwords' to there.

**Comment by xaniasd** [comment]
nice, thanks!
