### ISSUE TITLE
conflicting with camptocamp/archive

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-archive#165]
This module is conflicting with @camptocamp's archive
A sample issue from @voxpupuli's kafka: https://github.com/voxpupuli/puppet-kafka/issues/61

I'd like to get this issue resolved my making the two modules' inputs compatible.

paging @mcanevet & @raphink, and @nanliu.

**Comment by madAndroid** [comment]
I've experienced this very frequently - 👍 - would be great if this could be resolved somehow

**Comment by nanliu** [comment]
I wish it was as simple as mapping parameters, but I see several new parameters that need to be supported in archive and looks like some features are very specific to tar.

**Comment by raphink** [comment]
Should we try to merge the modules?

**Comment by jyaworski** [comment]
@raphink I would be open to merging them.

**Comment by nibalizer** [comment]
I would like to see them merge. How to do this?

**Comment by igalic** [comment]
There are two primary issues to make this module compatible with camptocamp/archive.

* camptocamp/archive doesn't have a class archive, and it probably cannot have such a thing

*******

## parameters

camptocamp/archive | voxpupuli/archive| name conflict | functionality conflict
---------------------------|-------------------------|-----------------|------------------------
ensure|ensure  | :white_check_mark: | :white_check_mark: 
name|name | :white_check_mark: | :white_check_mark: 
src_target | filename | :x: | :x: 
… | extract | :white_check_mark: | :x: camptocamp always extracts
target | extract_path | :x: | :white_check_mark: 
extension | … | :white_check_mark: | :x:
… | extract_command | :white_check_mark: | :x:
… | extract_flags | :white_check_mark:  | :x:
… | creates | :white_check_mark: | :x: hidden, not overridable in camptocamp
… | cleanup | :white_check_mark: | :x: no such thing in camptocamp
url | source | :x: | :white_check_mark:
checksum | checksum_verify | :x: | :white_check_mark: 
digest_url | checksum_url | :x: | :white_check_mark: 
digest_type | checksum_type | :x: | :white_check_mark: 
digest_string | checksum | :x: | :white_check_mark: 
… | cookie | :white_check_mark: | :x:
… | username | :white_check_mark: | :x:
… | password | :white_check_mark: | :x:
proxy_server | proxy_server | :white_check_mark: | :white_check_mark: 
… | proxy_type | :white_check_mark: | :x:
user | user | :white_check_mark: | :white_check_mark:
… | group | :white_check_mark: | :x:

**Comment by terrimonster** [comment]
@igalic I can't thank you enough for pushing this forward, and organizing that table.

**Comment by igalic** [comment]
first attempt, could be better, but it's a first ugly attempt https://github.com/voxpupuli/puppet-archive/pull/176

**Comment by igalic** [comment]
next up we'll need wrappers for archive::download (and archive::extract)
and tests.
but that doesn't quite solve the problem of camptocamp/archive not being able to provide a class archive :D

**Comment by bbriggs** [comment]
Is the idea to have full feature pairity across both or to assist people moving from camptocamp/archive into this one? If it's the latter, we should be okay with having a superset of camptocamp/archive's features.

**Comment by raphink** [comment]
Whichever way works best. If it's easier to add wrappers to camptocamp's module, I'll merge them. If you prefer to provide the API here so users of camptocamp's module can migrate, that's good too.

**Comment by bbriggs** [comment]
I think for now we should aim to have vp/archive be a superset of camptocamp/archive and backport any necessary features.

**Comment by joshuaspence** [comment]
+1

**Comment by igalic** [comment]
i think with #174 and #176 merged, we can close this one as ***good enough***
