### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by nibalizer** [voxpupuli/puppet-archive#172]
I'd like us to make a 1.0 release of this module. It's been long enough that we can commit to not breaking it. Plus the puppet modules team wants to approve it and make it a dependency for other modules.

@nanliu is there anything you were hoping to deprecate before a 1.x release is cut?

There are currently some changelog like bits in the Readme, those should be moved to the changelog or deleted.

Some of the defined types and features are marked as experimental in the Readme. Do we have enough faith that they have existed for long enough to mark them as non-expermiental? Even if we don't think they work in all cases, I figure we can commit to not totally changing their apis.

**Comment by nanliu** [comment]
@nibalizer I'll take some time this weekend to do a pass on this module and see if we need anything else before 1.0.0.

- [ ] migrate breaking change warning from README to CHANGELOG.
- [ ] commit on experimental features.

**Comment by igalic** [comment]
@nanliu ping

**Comment by nibalizer** [comment]
Let's do it!

**Comment by nanliu** [comment]
Released
