### ISSUE TITLE
`allow_insecure` parameter

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-archive#174]
It'd be good if the archive type had an `allow_insecure` parameter that worked much the same way as the [camptocamp/archive parameter](https://github.com/camptocamp/puppet-archive/blob/master/manifests/init.pp#L45) of the same name.

Useful for when you have an https server that is perhaps using a self-signed certificate.
In `wget` the option is ` --no-check-certificate` and in `curl` it is `--insecure`

**Comment by igalic** [comment]
:+1: for inching closer to #165
