### ISSUE TITLE
Windows https source not working

### ISSUE THREAD

**Issue by rigareau** [voxpupuli/puppet-archive#185]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2015.3
- Ruby: ruby 2.1.8p440 (2015-12-16 revision 53160) [x64-mingw32]
- Distribution: Windows Server 2012 r2
- Module version: 1.0

### How to reproduce (e.g Puppet code you use)
  archive { 'winsrv2012r2options.zip':
    ensure       => present,
    path         => 'c:\staging\winsrv2012r2options.zip',
    source       => 'https://myhost.mydomain.ca/microsoft/windows/winsrv2012r2options.zip',
    extract      => true,
    extract_path => 'c:\staging',
    creates      => 'c:\staging\sxs',
  }
### What are you seeing
Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=error: certificate verify failed at 42:/etc/puppetlabs/code/environments/development/modules/profile/manifests/mymodule.pp 
Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=error: certificate verify failed at 42:/etc/puppetlabs/code/environments/development/modules/profile/manifests/mymodule.pp
### What behaviour did you expect instead
A file to be present in the staging directory
### Any additional information you'd like to impart
I'm using an Entrust signed certificate on the source server.
From what I see the file cacert.pem that the ruby provider is trying to use when running under Windows is never transferred on the puppet node.  So it's not able to validate any certificates and fails reporting: error: certificate verify failed

**Comment by nanliu** [comment]
See if #186 resolves the issue. Also we should see if we can add untrusted certs for windows.

**Comment by nanliu** [comment]
Let us know if there are any issues. I will close this ticket during next sweep if there are no further updates.
