### ISSUE TITLE
AIX - extraction fails

### ISSUE THREAD

**Issue by winningpanthers** [voxpupuli/puppet-archive#194]
AIX does not have the GNU tar, tar -xzvf does not work in AIX and extraction fails. Can you please fix the issue?

### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by bastelfreak** [comment]
Hi @winningpanthers, thanks for reporting this. are you able to provide a patch or a PR for this?

**Comment by winningpanthers** [comment]
You're welcome. Still working on it. Will let you know.

**Comment by nanliu** [comment]
I'm guessing this should work like Solaris. Let me know if the fix works on AIX or if we should use a different set of commands since I don't have any AIX hardware to verify.

**Comment by winningpanthers** [comment]
Yes. thank you. I fixed this on my local and was about to upload the details. This works. Tested this on my AIX. Appreciate your help.
