### ISSUE TITLE
allow_insecure not at root level

### ISSUE THREAD

**Issue by dannythk** [voxpupuli/puppet-archive#195]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.X
- Ruby: 1.9.3
- Distribution: RHEL 6
- Module version: 1.0.0

### How to reproduce (e.g Puppet code you use)
Very simple, I think it affect all version. because it doesn't seem like "archive" accept allow_insecure parameter.  
  archive { '/tmp/<filename>:
    ensure        => present,
    source        => 'URI of the file',
    checksum_type => 'md5',
    checksum_url  => 'URI of the file.md5',
    extract       => true,
    extract_path  => 'some directory',
    creates       => 'some directory',
    allow_insecure => true
  }
The allow_insecure parameter is in "archive::download".

### What are you seeing
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter allow_insecure on Archive[filename]

### What behaviour did you expect instead
Successful retrieval?

**Comment by nanliu** [comment]
The allow_insecure parameter is definitely specified and spec tested: https://github.com/voxpupuli/puppet-archive/blob/master/spec/unit/puppet/type/archive_spec.rb#L21

This seems like a problem similar to #105 with deployment of types/providers. Are you deploying this in a multi-environment puppet master with multiple module version? See Puppet Labs [Server-94](https://tickets.puppetlabs.com/browse/SERVER-94) for more info.

**Comment by dannythk** [comment]
Yes, we do have multi-environments  in my puppet master, and some of the modules are at different version depend on the environment. 
I tried to move the archive module in "/etc/puppetlabs/puppet/modules", "/opt/puppet/share/puppet/modules", and "/etc/puppetlabs/puppet/environment/production/modules" directory, no luck in any of those.  
Upgrading is not an option for me at all (at least not the near future) nor having just one environment per puppet master node.

**Comment by dannythk** [comment]
This ticket could be closed.  It does work in an isolated environment.  Just trying to come up with a work around in our multi environments puppet server.
