### ISSUE TITLE
Add support for timeout

### ISSUE THREAD

**Issue by phathocker** [voxpupuli/puppet-archive#196]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.4.2
- Ruby: ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
- Distribution: RHEL7
- Module version: 1.0.0

### How to reproduce (e.g Puppet code you use)
```
  archive { "${destination_dir}/${package_name}":
    ensure       => $ensure,
    source       => $java_url,
    cleanup      => false,
    extract_path => $destination_dir,
    timeout      => $download_timeout,
    cookie       => $cookie,
    proxy_server => $proxy_server,
    proxy_type   => $proxy_type,
    notify       => [
      Exec[$exec_name],
    ],
  }
```

### What are you seeing
I have some downloads that are timing out because of either high volume on the destination or congestion on certain network hops.  I would love to be able to set the timeout longer to avoid these timeouts.

### What behaviour did you expect instead
Ability to increase timeout value

**Comment by nanliu** [comment]
Can you provide the output from --trace, I'm not immediately seeing how a timeout is triggered from the provider, so it _should_ be unlimited. A timeout exist for the exec resource provider, but not Puppet::Util.execute or the generated command methods such as curl(), wget().

**Comment by nanliu** [comment]
Please feel free to reopen this if you have more information or logs pointing to the module providers causing a timeout.

**Comment by phathocker** [comment]
I think I'm good.  Looks like I wasn't setting the proxy correctly in hiera.
