### ISSUE TITLE
archive_windir fact doesn't work on Ruby 1.8.7

### ISSUE THREAD

**Issue by treydock** [voxpupuli/puppet-archive#199]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.6
- Ruby: 1.8.7
- Distribution: RHEL6
- Module version: 1.0.0

### What are you seeing

Facter syntax errors

### What behaviour did you expect instead

No errors

### Output log

```
Error loading fact /var/lib/puppet/lib/facter/archive_windir.rb: /var/lib/puppet/lib/facter/archive_windir.rb:2: syntax error, unexpected ':', expecting kEND
  confine osfamily: :windows
```

### Any additional information you'd like to impart

The hash style used in the archive_windir fact does not work in Ruby 1.8.7 which is used by RedHat 6.

**Comment by nanliu** [comment]
The latest version of this module does not support ruby 1.8.7. See release note for deprecation info.
