### ISSUE TITLE
archive::nexus ignore changes

### ISSUE THREAD

**Issue by myMarck** [voxpupuli/puppet-archive#204]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.5
- Ruby: 1.9.3p484
- Distribution: Ubuntu 14.0.4
- Module version: 1.1.1

### How to reproduce (e.g Puppet code you use)
Run the example code in nexus::archive

   archive::nexus { '/tmp/jtstand-ui-0.98.jar':
     url        => 'https://oss.sonatype.org',
     gav        => 'org.codehaus.jtstand:jtstand-ui:0.98',
     repository => 'codehaus-releases',
     packaging  => 'jar',
     extract    => false,
   }

ls -al /tmp/jtstand-ui-0.98.jar 
-rw-r----- 1 root root 286643 Aug 29 12:02 /tmp/jtstand-ui-0.98.jar

change the file size to zero by doing

sudo rm /tmp/jtstand-ui-0.98.jar && sudo touch /tmp/jtstand-ui-0.98.jar

run puppet again

### What are you seeing

ls -al /tmp/jtstand-ui-0.98.jar 
-rw-r--r-- 1 root root 0 Aug 29 12:04 /tmp/jtstand-ui-0.98.jar

### What behaviour did you expect instead

I would expect the archive module to replace the file.

### Output log
NA

### Any additional information you'd like to impart
It works in version 0.5.1
This problem also affects SNAPSHOT dependencies that are not replaced when new archives exsists in the repository

**Comment by nanliu** [comment]
@myMarck, check and see if #211 resolves this issue
