### ISSUE TITLE
Getting error while running puppet archive.

### ISSUE THREAD

**Issue by atmesh** [voxpupuli/puppet-archive#205]
I am using puppet-archive to download my file from a repository.
```
archive { "/usrdata/archive/${tomcat::jreversion}":
  ensure       => present,
  extract      => true,
  extract_path => '/usrdata/apps/java/',
  source       => $tomcat::params::jredownloadpath,
  creates      => "/usrdata/apps/java/${tomcat::jdkversion}",
}
```

### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 2.0.0
- Module version: 1.1.0

### How to reproduce (e.g Puppet code you use)

I am using puppet-archive to download my file from a repository.
```
archive { "/usrdata/archive/${tomcat::jreversion}":
  ensure       => present,
  extract      => true,
  extract_path => '/usrdata/apps/java/',
  source       => $tomcat::params::jredownloadpath,
  creates      => "/usrdata/apps/java/${tomcat::jdkversion}",
}
```

### What are you seeing
But I get the following error on puppet run -:

> Error: Could not set 'present' on ensure: no implicit conversion of nil into String at 26:/etc/puppet/modules/tomcat/manifests/javaora.pp
> Error:Could not set 'present' on ensure: no implicit conversion of nil into String at 26:/etc/puppet/modules/tomcat/manifests/javaora.pp Wrapped exception: no implicit conversion of nil into String Error: /Stage[main]/Tomcat::Javaora/Archive[/usrdata/archive/jre-7]/ensure: change from absent to present failed: Could not set 'present' on ensure: no implicit conversion of nil into String at 26:/etc/puppet/modules/tomcat/manifests/javaora.pp

### What behaviour did you expect instead

I expected it to download the archived file from the source and extract at desired location

**Comment by nanliu** [comment]
Can you run this with --trace and provide line 26 of javaora.pp (or highlight the line in the manifests you provided)

**Comment by atmesh** [comment]
@nanliu the closing curly brace just below `creates` is line:26 of my manifest.

**Comment by atmesh** [comment]
can you explain the possible reason why I am experiencing this behaviour? Just  hint on what could be wrong!

**Comment by nanliu** [comment]
It's an issue converting a string, most likely source parameter is nil. Can't provide more detail without the --trace to pinpoint the ruby source code line number and a stack trace.

**Comment by nanliu** [comment]
So I did a local test and your source parameter is undefined. I'll write a patch to make sure we raise a more meaningful error.

**Comment by atmesh** [comment]
Seems like it is not able to find the path! Closing the issue.
