### ISSUE TITLE
Some Gem dependencies require Ruby > 2.1

### ISSUE THREAD

**Issue by alexharv074** [voxpupuli/puppet-archive#221]
When running a bundle install I'm getting Gem dependency issues.

### Affected versions/distributions

- Ruby: 2.0.0p481

### How to reproduce

```
$ bundle install
```

### Actual behaviour

```
Installing ruby_dep 1.4.0

Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

and then later

```
Installing listen 3.1.5

Gem::InstallError: listen requires Ruby version >= 2.2.3, ~> 2.2.
```

### Expected behaviour

All Gems should install.

**Comment by bastelfreak** [comment]
Hi,
We are aware of the issue. Ruby2.1 is kind-of EOL and only gets security updates.However you should still be able to install needed tests with this command:
```
bundle install --without system_tests development
```

**Comment by alexharv074** [comment]
I could be out of date, but isn't Puppet itself shipped with Ruby 2.1.x?

**Comment by bastelfreak** [comment]
The puppet-aio packages ship a bundled ruby21, yeah. But the required gems for testing have nothing to do with a running puppet environment.

**Comment by bastelfreak** [comment]
Why do you want to install the gems? Do you want to run the tests? We created the gem groups with much care to ensure that they also work on ruby193 and everything newer.

**Comment by alexharv074** [comment]
Yes, to run the tests.  As a Puppet developer, I install Ruby 2.1 everywhere for consistency with Puppet.  I would think most people do this?

**Comment by bastelfreak** [comment]
Personally I use system-ruby which is currently ruby231. Our spec tests are designed to work with the provided bundler snippet I posted above. Only the rubocop test/raketask requires ruby231.

**Comment by alexjfisher** [comment]
@bastelfreak I've just confirmed that all the gems needed to run the spec tests still install fine on ruby 1.9 (when using `bundle install --without system_tests development`)

@alexharv074 The module is tested against several different versions of ruby. Take a look in the https://github.com/voxpupuli/puppet-archive/blob/master/.travis.yml to see what we currently test against.  Are you using rvm?

**Comment by alexharv074** [comment]
It's no big deal.  I already worked around it.  I just thought most Puppet programmers would set up their environments to please Puppet.  Feel free to decline the PR.
