### ISSUE TITLE
Syntax Error with Ruby 1.8.7.374 that doesn't happen with Ruby 2.0.0.598

### ISSUE THREAD

**Issue by vmorate** [voxpupuli/puppet-archive#224]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 1.8.7
- Distribution: RHEL 6.6
- Module version: 1.1.2

### How to reproduce (e.g Puppet code you use)

Create a test.pp file with the following code:

archive { 'test':
      source       => 'http://pkg.jenkins-ci.org/redhat/jenkins-1.651-1.1.noarch.rpm',
      path         => '/opt',
      cleanup      => false,
      extract      => false,
    }

Using a RHEL 6.6 Vagrant machine execute:

puppet apply /vagrant/test.pp --modulepath $archiveModulePath

### What are you seeing

Error: Could not autoload puppet/type/archive: /vagrant/modules/archive/lib/puppet/type/archive.rb:53: syntax error, unexpected ':', expecting ')'
  newparam(:path, namevar: true) do
                          ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting ')'
...aram(:allow_insecure, boolean: true, parent: Puppet::Paramet...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: Can't assign to true
...allow_insecure, boolean: true, parent: Puppet::Parameter::Bo...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting '='
...secure, boolean: true, parent: Puppet::Parameter::Boolean) d...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ')', expecting $end
...t: Puppet::Parameter::Boolean) do
                              ^
Error: Could not autoload puppet/type/archive: /vagrant/modules/archive/lib/puppet/type/archive.rb:53: syntax error, unexpected ':', expecting ')'
  newparam(:path, namevar: true) do
                          ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting ')'
...aram(:allow_insecure, boolean: true, parent: Puppet::Paramet...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: Can't assign to true
...allow_insecure, boolean: true, parent: Puppet::Parameter::Bo...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting '='
...secure, boolean: true, parent: Puppet::Parameter::Boolean) d...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ')', expecting $end
...t: Puppet::Parameter::Boolean) do
                              ^ on node infragvp.vagrant
Error: Could not autoload puppet/type/archive: /vagrant/modules/archive/lib/puppet/type/archive.rb:53: syntax error, unexpected ':', expecting ')'
  newparam(:path, namevar: true) do
                          ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting ')'
...aram(:allow_insecure, boolean: true, parent: Puppet::Paramet...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: Can't assign to true
...allow_insecure, boolean: true, parent: Puppet::Parameter::Bo...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ':', expecting '='
...secure, boolean: true, parent: Puppet::Parameter::Boolean) d...
                              ^
/vagrant/modules/archive/lib/puppet/type/archive.rb:223: syntax error, unexpected ')', expecting $end
...t: Puppet::Parameter::Boolean) do
                              ^ on node infragvp.vagrant

### What behaviour did you expect instead

No error shown, same code on RHEL 7.2 with Ruby 2.0.0.598 is working fine

**Comment by alexjfisher** [comment]
@vmorate This module dropped support for ruby 1.8 in version 1.0.0
https://github.com/voxpupuli/puppet-archive/blob/master/CHANGELOG.md#2016-07-13-release-100

You can still use it on EL6 with puppet 4 which ships with its own ruby.

**Comment by vmorate** [comment]
Thank you very much @alexjfisher , we will upgrade to Puppet 4 to be able to use archive without errors.

**Comment by vmorate** [comment]
As provisional Workaround we have downgrade the puppet-archive module to archive [V0.5.1 ](https://github.com/voxpupuli/puppet-archive/releases/tag/v0.5.1) using the release tag defined for that purpose.

**Comment by bastelfreak** [comment]
@vmorate please ping us if you need any help in upgrading your OS, Ruby Version or Puppet. We're 24/7 reachable in #voxpupuli on freenode and happy to help out.

**Comment by v6** [comment]
// , @vmorate , how did the upgrade go?

**Comment by vmorate** [comment]
Everything working again. Thanks!

**Comment by xudingding978** [comment]
Hi, I also meet this issue when I use Puppet 3.8.7, ruby 2.0.0p648 on RHEL 6.7
Any ideas why?

Thanks

**Comment by tuxmea** [comment]
@xudingding978 as mentioned above: Puppet 3 and ruby 1.8 support was dropped.
You are asked to either upgrade to Puppet 4 or use v0.5.1 tag from archive module.
