### ISSUE TITLE
Server Error: no parameter named 'provider'

### ISSUE THREAD

**Issue by antoineco** [voxpupuli/puppet-archive#249]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.1
- Ruby: 2.3.1
- Distribution: CentOS 7, Debian 8
- Module version: 1.1.2

## How to reproduce (e.g Puppet code you use)

[Code example](https://github.com/antoineco/aco-oracle_java/blob/373c89b893f81e21b3d98d74c67e0be8721c8ef5/manifests/download.pp#L35-L40)

## What are you seeing

In agent mode (client-server) Puppet fails with an error 500 if `provider => 'curl'` is set on any `archive` resource.

`puppet apply` works with the same code.

## What behaviour did you expect instead

Puppet should be able to request and apply the catalog whether the `provider` parameter is set or not.

## Output log

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'provider' at /etc/puppetlabs/code/environments/osb2/modules/oracle_java/manifests/download.pp:35 on Archive[/usr/java/jdk-8u111-linux-x64.rpm] at /etc/puppetlabs/code/environments/osb2/modules/oracle_java/manifests/download.pp:35 on node dosbdevadm01.dev.somecool.place
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Any additional information you'd like to impart

Bug reported in a downstream module: https://github.com/antoineco/aco-oracle_java/issues/26
*Could* be related to #105.

**Comment by alexjfisher** [comment]
I think very likely related to https://github.com/voxpupuli/puppet-archive/issues/105.  Make sure you've got puppet-archive in all your environments (and especially in the environment your puppet master uses).  If you can do that, this issue *should* go away.

And vote for https://tickets.puppetlabs.com/browse/SERVER-94 !

**Comment by juniorsysadmin** [comment]
Closing for now, re-open if need be
