### ISSUE TITLE
wget proxy implementation incorrect

### ISSUE THREAD

**Issue by walkamongus** [voxpupuli/puppet-archive#256]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.7.0
- Ruby: 2.1.9
- Distribution: Centos
- Module version: 1.2.0

## How to reproduce (e.g Puppet code you use)
 just set `proxy_server => 'https://example.org:8080'` and `provider => 'wget'`

## What are you seeing
The proxy server is passed as `--https_proxy=https://example.org:8080` to the `wget` command. This triggers a `returned 2: wget: unrecognized option '--https_proxy=https://example.org:8080'` error messages.

## What behaviour did you expect instead
I'd expect the following options to be passed to wget: `-e use_proxy=yes -e https_proxy=https://example.org:8080`

## Output log
```
returned 2: wget: unrecognized option '--https_proxy=https://example.org:8080'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

**Comment by bastelfreak** [comment]
Hi @walkamongus, thanks for the PR. Are you able to provide a fix for this?

**Comment by walkamongus** [comment]
Hi @bastelfreak -- I'll try to knock something up this weekend.
