### ISSUE TITLE
Does this module rerun after each download/extract ?

### ISSUE THREAD

**Issue by Yamakasi** [voxpupuli/puppet-archive#258]
How is there checked if te download or extract needs to be done again ? I see lots of modules rerun every time and I want to void that or be able to rerun when I have an updated tar/zip with some other buildname or so.

Thanks!

**Comment by Yamakasi** [comment]
Seems to be covered.

**Comment by LewR1344** [comment]
Where did you find the answer to your question?  We are using this module to download and extract zip archives on linux, but it doesn't seem to rerun when the source zip file changes.
