### ISSUE TITLE
Extract one folder in zipped file

### ISSUE THREAD

**Issue by Yamakasi** [voxpupuli/puppet-archive#259]
Hi,

Is it possible to extract only one (or maybe more) folder(s) from a .zip/.tar.gz/.etc ?

Thanks

**Comment by nanliu** [comment]
You should be able to by specifying a custom extract command:

```puppet
archive { 'example.tgz':
  extract_command => 'tar -xvf %s single/folder',
  ...
}
```

The code should do the following in ruby to get the command: `resource[:extract_command] % @file_path`.
