### ISSUE TITLE
feature: Artifactory authentication support

### ISSUE THREAD

**Issue by ngeorgieff** [voxpupuli/puppet-archive#265]
Currently archive::artifactory doen't not accept username and password.
It will be very helpful if we can download artifacts with authentication

**Comment by mglambet** [comment]
+1 on this. Support of the X-JFrog-Art-Api header would do the trick.

**Comment by krisamundson** [comment]
+1

I have a customer requiring this feature. We are looking at the code now and we'll see if we can provide a patch.

**Comment by the-linux-guy** [comment]
+1
Username or password or even bettwen the API key

**Comment by Simoliv** [comment]
+1 for X-JFrog-Art-Api , thought I could use download_options, but seems not working
