### ISSUE TITLE
Add guide for migrating from puppet-staging

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-archive#266]
Before we deprecate puppet-staging, we should enhance the puppet-archive README with some migration docs.

**Comment by alexjfisher** [comment]
A couple of examples have been added to the README.
@binford2k Are you happy with these, or would you like some more?

Or maybe links to real-world examples (eg PRs in other forge modules)??

**Comment by binford2k** [comment]
Looks great to me. PR links to ports could be nice, but probably not worth the effort. :thumbsup:

**Comment by alexjfisher** [comment]
@binford2k Thanks.  I'll close this.  Feel free to review https://github.com/voxpupuli/puppet-staging/pull/137
