### ISSUE TITLE
Support puppet:/// urls or edit readme?

### ISSUE THREAD

**Issue by 7yl4r** [voxpupuli/puppet-archive#283]
## What are you seeing
The readme provides an example using a "puppet:/// style url which is not currently supported."

## What behaviour did you expect instead
Why is this included if it is not supported? Is it planned for implementation soon?

## Any additional information you'd like to impart
I think I may just be confused here, but perhaps a quick change to the readme would be helpful. Is #77 an implementation of this functionality but the readme was overlooked?

**Comment by 7yl4r** [comment]
After working with this a bit I've found that the readme is describing a workaround. The readme may need to clarify this point a bit. Additionally, is there an open feature request for supporting `puppet://` urls without the workaround?

**Comment by alexjfisher** [comment]
See https://github.com/voxpupuli/puppet-archive/pull/270

**Comment by alexjfisher** [comment]
@7yl4r Sorry for the brevity earlier (I didn't realise my train was pulling into the station!).

Being able to use `puppet:///` URLs is a feature we're hoping to merge 'real soon now'.

**Comment by 7yl4r** [comment]
I figured there must be something ongoing somewhere, but couldn't find it this morning. Thanks!

**Comment by hajee** [comment]
I think this one can be closed, since #270 has been merged and provides just this.

**Comment by igalic** [comment]
do we have a version with this feature released yet?

**Comment by alexjfisher** [comment]
@igalic Not yet, but I think we should go ahead with a release now.

**Comment by hajee** [comment]
So what are the steps and the timeline you have in mind?

**Comment by igalic** [comment]
yes @hajee ! https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module please! help…

**Comment by alexjfisher** [comment]
@hajee I made a start by doing a modulesync, but then ran out of time before going on holiday.
You could create a release PR but normally the changelog will need improving by updating various issues  and PRs with the correct labels etc. Do you want to open the release PR anyway to see how we're looking?  I've only got my phone with me, so can't be much more help until I return home on Friday.

**Comment by hajee** [comment]
I'll see what I can do.

**Comment by nanliu** [comment]
Closed since v2.0.0 is released with puppet:///
