### ISSUE TITLE
Upgradable Archives

### ISSUE THREAD

**Issue by pioto** [voxpupuli/puppet-archive#286]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.7.1
- Ruby: 2.1.9
- Distribution: RHEL 7
- Module version: 1.3.0

## How to reproduce (e.g Puppet code you use)

Use `archive` with `extract`, `creates`, and `source`.

## What are you seeing

If the `source` URL changes, the archive will not be downloaded or extracted again.

## What behaviour did you expect instead

I would expect the new archive to be downloaded and extracted.

## Any additional information you'd like to impart

Many modules are using this module to download distributions of 3rd party software which isn't available as a standard distribution package (.deb, .rpm, etc). To match the expectations of many of those module's users, it would be helpful if the archive module maintained some sort of state, probably outside of the `extract_path`, and somewhere private to this module in `/var`. When the `source` changes, it should force a fresh extract.

Alternatively, we could have some sort of additional parameter, like `version`, with similar semantics.

**Comment by nanliu** [comment]
the way the module determines whether a file should be downloaded is by using the file checksum. there are some changes to use timestamp such as implementation to use latest. the url source is a parameter and not used to determine whether a file is downloaded.
