### ISSUE TITLE
unzip not installed and results in errors

### ISSUE THREAD

**Issue by Justin-DynamicD** [voxpupuli/puppet-archive#291]
fairly simple really, but the module doesn't actually check/validate if unzip s actually installed and thus can return errors when called from "minimal" linux boxes (aka base installs with no optional features).  As you already require stdlib for use,  I think adding an ensure_packages statement would be helpful to ensure "expected" operation.

**Comment by nanliu** [comment]
See [documentation setup section](https://github.com/voxpupuli/puppet-archive#setup) for recommended configuration, we leave the dependencies up to the user to specify since it varies across environments and there isn't a single good default.
