### ISSUE TITLE
allow_insecure is not working

### ISSUE THREAD

**Issue by lmayorga1980** [voxpupuli/puppet-archive#294]
I am trying to download a file to a specific location(no compress/decompress)

```ruby
 archive::download { 'gitlab-ci-multi-runner.rpm':
    url            => "https://myserver/gitlab-ci-multi-runner.rpm",
    allow_insecure => true,
  }
```

```
(60) Peer's certificate issuer has been marked as not trusted by the user.
==> : More details here: http://curl.haxx.se/docs/sslcerts.html
==> : 
==> : curl performs SSL certificate verification by default, using a "bundle"
==> :  of Certificate Authority (CA) public keys (CA certs). If the default
==> :  bundle file isn't adequate, you can specify an alternate file
==> :  using the --cacert option.
==> : If this HTTPS server uses a certificate signed by a CA represented in
==> :  the bundle, the certificate verification probably failed due to a
==> :  problem with the certificate (it might be expired, or the name might
==> :  not match the domain name in the URL).
==> : If you'd like to turn off curl's verification of the certificate, use
==> :  the -k (or --insecure) option.
```

**Comment by alexjfisher** [comment]
@lmayorga1980 Thanks for your bug report.  This should be easy enough to fix.

But first, are you aware you're using the camptocamp/archive compatibility class?
Can you use the `archive` type directly?

@igalic Added the camptocamp compatibility in https://github.com/voxpupuli/puppet-archive/pull/176
I added the `allow_insecure` option shortly after in https://github.com/voxpupuli/puppet-archive/pull/180.  It wasn't until https://github.com/voxpupuli/puppet-archive/pull/198 before it became available for all providers.  https://github.com/voxpupuli/puppet-archive/blob/master/manifests/download.pp was never updated.

**Comment by alexjfisher** [comment]
@igalic Does https://github.com/voxpupuli/puppet-archive/pull/295 look ok to you?
