### ISSUE TITLE
Could not autoload puppet/type/archive

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-archive#302]
## Output log
The error message is quite confusing, I had no idea what's going on. 
```
 Could not autoload puppet/type/archive: Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/archive'. Set at unknown location on node ...
```

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.8
- Ruby: 2.3.3p222
- Distribution: Debian 9
- Module version: 1.3.0, 2.1.0

## How to reproduce (e.g Puppet code you use)
I've started seeing this error after making computing checksum optional:
```puppet
if !empty($install_checksum) {
    Archive<| title == "${download_dir}/dcos_install.sh" |> {
      checksum      => $install_checksum['hash'],
      checksum_type => $install_checksum['type'],
    }
}
```
After removing this part of code everything works fine.

**Comment by kenyon** [comment]
Maybe same as #347. Also obsolete versions.
