### ISSUE TITLE
Could not autoload puppet/parser/functions/artifactory_sha1: no such file to load -- puppet_x/bodeco/util

### ISSUE THREAD

**Issue by asociadoC** [voxpupuli/puppet-archive#320]
Thats somehow annoying .. I cant progress with my work at the moment .. 

Whats wrong here ?

`
[root@qa5 disk2]# puppet agent -t --server puppet --environment cm
Info: Using configured environment 'cm'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/artifactory_sha1: no such file to load -- puppet_x/bodeco/util at /etc/puppetlabs/code/modules/archive/manifests/artifactory.pp:103:14 at /etc/puppetlabs/code/modules/our_application/manifests/deployer.pp:53 on node qa5
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
`

[root@qa5 disk2]# puppet agent --version
5.3.3

**Comment by jtmfam** [comment]
We are experiencing this issue (#320) in production now.  Please merge in #329 now to please fix our problem.  Thanks.

**Comment by wolbi** [comment]
In puppet-archive 4.4.0 problem still exists. Could you please merge above patch ?
