### ISSUE TITLE
Still 2 Certificates expired  in cacert.pem

### ISSUE THREAD

**Issue by vlours** [voxpupuli/puppet-archive#376]
Hi Guys,

Just a follow up on issue #372 
2 expiring Certificates were not updated in the latest ca.pem file.
Could you please generate a new ca.pem file and ensure that no certificate are expired.
Based on my last extract, the next expiring certificate should be:
| 2020-03-25 | Staat der Nederlanden Root CA - G2 |

## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: 4.1.0.0

## How to reproduce (e.g Puppet code you use)

- Check the content of the cacert.pem file:
openssl crl2pkcs7 -nocrl -certfile lib/puppet_x/bodeco/cacert.pem | openssl pkcs7 -print_certs -text -noout

## What are you seeing

Since the last certificate update on 4th July (Issue #372), 2 certificates have expired.
| 2019-07-06 | Class 2 Primary CA |
| 2019-07-09 | Deutsche Telekom Root CA 2 |

## What behaviour did you expect instead
No expired certificates.

## Any additional information you'd like to impart
This issue is purely informative. There is no impact in our side.
You may have to link in the documentation the way to regenerate this file.

Cheers,
Vincent

**Comment by alexjfisher** [comment]
The file comes directly from https://curl.haxx.se/docs/caextract.html and we’ve not made any attempts to further refine it. It only gets updated every few months (but we could definitely do better at replacing the module’s version more frequently).

**Comment by vlours** [comment]
Hi Alex,

Thanks for your message and for sharing the method you're currently using to retrieve the cacert.pem file.

From this information, I was able to create a custom Path to retrieve the latest cacert.pem using the command "**mk-ca-bundle.pl**"

For more portability, I've defined a docker image to do it.
- Here after is the Dockerfile to build the image: 
```
FROM centos:latest
RUN yum install curl perl-libwww-perl -y --nogpgcheck
RUN curl https://raw.githubusercontent.com/curl/curl/master/lib/mk-ca-bundle.pl -o /tmp/mk-ca-bundle.pl
RUN mkdir /mysharefolder
CMD perl /tmp/mk-ca-bundle.pl /mysharefolder/cacert.pem
```
- To build the docker image: 
`docker build -t cacert <path_of_Dockerfile>`
- To run the container and retrieve the file in your desired folder:
`docker run --rm -v <desired_PATH>://mysharefolder cacert`
The file will be downloaded from Firefox "Release" and converted to a cacert.pem file, stored in your desired PATH.
This should provide you a better way to manage the cacert.pem file in your future releases.

Unfortunately, the current version of the Firefox bundle is still including the expired certificates:
| 2019-07-06 | Class 2 Primary CA |
| 2019-07-09 | Deutsche Telekom Root CA 2 |

I will check it later next week(s), and submit a PR when available.

Have a great week-end.
Cheers,

**Comment by alexjfisher** [comment]
My understanding is that as soon as Mozilla change their bundle, curl (the organisation), will regenerate the file and publish it on their website.  They claim to already perform the check daily.

**Comment by vlours** [comment]
You're right, I did not read the first lines. As was looking to get the data extraction first :)
So as this is definitely related to Firefox CA bunble certificates, I've created a "question" in the Firefox support forum.
I hope they will update their CA bunble soon to update/remove the expired CA certificates.

I will let you know when it will be done.

**Comment by igalic** [comment]
I'm sure there should be a bugzilla issue on Mozilla's side. we should link it here

**Comment by l-avila** [comment]
I messed up my PR last week and failed to link to this issue. But #444 should fix the problem stated here. Thank you.
