### ISSUE TITLE
Extract .zip using PowerShell (native) as alternative to 7-zip

### ISSUE THREAD

**Issue by azbarcea** [voxpupuli/puppet-archive#380]
I would like to add support to extract .zip using PowerShell (the native .zip). This can be supported only from `2008+`, where `.zip` extraction is supported.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.5
- Ruby: ruby 2.0.0p648
- Distribution: 6.10
- Module version: latest

## How to reproduce (e.g Puppet code you use)
Use `archive` on `windows` without capability to install `7-zip`.

## What are you seeing
TODO:

## What behaviour did you expect instead
TODO:

## Output log
TODO:

## Any additional information you'd like to impart
TODO:

**Comment by ralfbosz** [comment]
Looking at this commit it seems to be included:

https://github.com/voxpupuli/puppet-archive/commit/9b808ad5dd83c5bcc0fb4b9db067e2b9a82a5d63

But for Windows 2012 and higher. 7zip is still the preferred unzipper (according to the code).

**Comment by azbarcea** [comment]
Looks good to me :+1:
