### ISSUE TITLE
Missing v.4.5.0 archive

### ISSUE THREAD

**Issue by jcapiitao** [voxpupuli/puppet-archive#410]
Hi folks,

It looks like this [PR](https://github.com/voxpupuli/puppet-archive/pull/404) has not been tagged as 'v4.5.0', as per the last releases. IIUC this is the reason the [archive](https://github.com/voxpupuli/puppet-archive/archive/v4.5.0.tar.gz) is not available.

Could you confirm/infirm please ?

Thanks,
Joe

**Comment by alexjfisher** [comment]
Thanks.  You were right that the release process hadn't been run correctly. 4.5.0 is on the forge now.
