### ISSUE TITLE
no parameter named 'provider' 

### ISSUE THREAD

**Issue by Simoliv** [voxpupuli/puppet-archive#446]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.1.2
- Ruby:
- Distribution: ubuntu server
- Module version: master

## How to reproduce (e.g Puppet code you use)
use provider as it is described in docs

## What are you seeing
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'provider' (file: /etc/puppetlabs/code/environments/production/modules/application/manifests/deployer.pp, line: 107) on Archive[package.tar.gz] (file: /etc/puppetlabs/code/environments/production/modules/application/manifests/deployer.pp, line: 107) on node puppet-dev-a.puppet.local`

## What behaviour did you expect instead
Works and I can set provider to wget

**Comment by kenyon** [comment]
I think we'll need to see the Puppet code you're using.

**Comment by Simoliv** [comment]
` root@puppet-dev:/etc/puppetlabs/code/environments/production# puppet generate types --environment production  
...
...

`

did the trick in that case
