### ISSUE TITLE
curl provider: array of multiple headers does not work

### ISSUE THREAD

**Issue by sprankle** [voxpupuli/puppet-archive#481]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: **6.1.0**

## How to reproduce (e.g Puppet code you use)

```puppet
  archive { "example.yml":
    path             => "/tmp/example.yml",
    source           => "https://github.com/examplefile.yml",
    extract_path     => /opt/new/dir,
    headers          => [
      'Accept: application/vnd.github.raw',
      "Authorization: Bearer ${github_token}",
    ],
    provider         => 'curl',
    cleanup          => false,
  }
```

## What are you seeing
Only the first `--header` flag is available at execution
`--header 'Accept: application/vnd.github.raw'`

## What behaviour did you expect instead
Repition of headers
`--header 'Accept: application/vnd.github.raw' --header 'Authorization: Bearer xxx_example_token'`

**Comment by kenyon** [comment]
Looks like this is a bug in #475.
