### ISSUE TITLE
Default for cleanup not correct

### ISSUE THREAD

**Issue by Fabian1976** [voxpupuli/puppet-archive#533]
According to the documentation, the default value for `cleanup` should be `false`. But in the code the default is set to `true` at this line: 
https://github.com/voxpupuli/puppet-archive/blob/63474f6709e4c44b1b4c6852b32335f34df32877/lib/puppet/type/archive.rb#L117

I found this when i was troubleshooting why my archive was being cleaned up when the parameter was not set. Expecting it to default to `false`.

**Comment by kenyon** [comment]
Where do you see the incorrect documentation?

**Comment by kenyon** [comment]
Maybe you were looking at the documentation for `archive::artifactory`: https://github.com/voxpupuli/puppet-archive/blob/63474f6709e4c44b1b4c6852b32335f34df32877/manifests/artifactory.pp#L56

**Comment by Fabian1976** [comment]
I found it on this location:
https://github.com/voxpupuli/puppet-archive/blob/master/REFERENCE.md#cleanup

**Comment by kenyon** [comment]
Yes, that is for the `archive::artifactory` defined type. That is distinct from the `archive` type.
