### ISSUE TITLE
Out of memory while downloading large files

### ISSUE THREAD

**Issue by pall-valmundsson** [voxpupuli/puppet-archive#55]
While trying to download a large .zip file (1.3GB) in a test VM with 512MB of RAM the only output I got from the puppet run was `Killed`. I increased the VM RAM incrementally and got `Error: Could not run: failed to allocate memory` until I had increased the RAM to 2GB, i.e. the file could be stored in RAM as a whole until flushed to disk.

Is this a known unfixable issue? Or an issue with the provider implementation? Or is there some workaround that can be applied?

**Comment by nibalizer** [comment]
Are you pulling the file over http or ftp?

**Comment by pall-valmundsson** [comment]
Ah, sorry I left that out. This is a HTTP Basic Auth pull.

**Comment by nibalizer** [comment]
Looking a bit at the code, this looks like an issue in the faraday library. However I dont see an issue on the faraday bug tracker for it. I'll try to find some time to bang on it today.

**Comment by pall-valmundsson** [comment]
Thanks for looking into this. Other potentially important information.
Puppet 3.7.5
CentOS 6
and therefore Ruby 1.8.7

**Comment by nibalizer** [comment]
I am able to reproduce the problem at least.

**Comment by nanliu** [comment]
In this case might as well swap out faraday with net/http and eliminate a dependency. I'll take a crack at it over next few days.

**Comment by nibalizer** [comment]
@nanliu do you think its in faraday? Is the typical pattern in puppet to hold in ram before file flushing? I'm just not experienced enough to know.

**Comment by nanliu** [comment]
I thought this was one of things I verified early on, but clearly missed it when evaluating faraday. Per their roadmap: https://github.com/lostisland/faraday/wiki/Roadmap and open PR: https://github.com/lostisland/faraday/pull/156, I don't think we are able to do streaming with faraday. net/http will require some code to handle http errorcodes and redirect, but will support streaming.

**Comment by jyaworski** [comment]
Since it looks like the Faraday PR is stalled, should we move to net/http or similar?

**Comment by nanliu** [comment]
Yes, we should switch to net/http as default provider.
