### ISSUE TITLE
checksum_url not working for me

### ISSUE THREAD

**Issue by dannythk** [voxpupuli/puppet-archive#72]
I get error when I utilize the checksum_url parameter.  

My code:
```puppet
  archive { "<file_name>":
    ensure        => present,
    source        => "$fileSourceURL",
    checksum_type => 'md5',
    checksum_url  => '$fileSourceChecksumURL',
    cleanup       => false,
  }
```
Error message: 
```
Error: /Stage[main]/[module_name]/Archive[[file_path]]: Could not evaluate: undefined method `content' for #<PuppetX::Bodeco::FTP:0x000000025843f8>
/var/opt/lib/pe-puppet/lib/puppet_x/bodeco/util.rb:15:in `content'
/<module_path>/archive/lib/puppet/provider/archive/ruby.rb:71:in `remote_checksum'

/var/opt/lib/pe-puppet/lib/puppet_x/bodeco/util.rb line 15
@connection.content(uri)

/<module_path>/archive/lib/puppet/provider/archive/ruby.rb  line 71
@remote_checksum ||= PuppetX::Bodeco::Util.content(resource[:checksum_url], :username => resource[:username], :password => resource[:password], :cookie => resource[:cookie])
```
My checksum_url = ftp://<hostname>/<filepath>/filename.txt

Checksum file content:
```
<checksum>  <file_name>
```
Configuration:
Puppet 3.8.1 on RHEL 6
puppetlabs-pe_gem (v0.1.1)
puppetlabs-stdlib (v4.6.0)
```json
  "dependencies": [
    {
      "name": "puppetlabs/stdlib",
      "version_requirement": ">= 2.2.1"
    },
    {
      "name": "puppetlabs/pe_gem",
      "version_requirement": ">= 0.0.1"
    }
  ]
```
Am I missing a dependency that I am not aware of?

**Comment by nanliu** [comment]
1. ftp:////filename.txt isn't really valid path.
2. the content method is only implemented for HTTP(s), not FTP.

If you wish to support ftp protocol as a remote_url, please implement content fetching for ftp.

**Comment by dannythk** [comment]
I am not familiar with RUBY script, but I was looking at the puppet_x/bodeco/util.rb and noticed there is a class for FTP.  That is why I thought FTP was supported.  

I tried to go down HTTP path as well, but it failed due to failed certificate check.  We usually provide "no-check-certificate" option which is not an option in the module.

For now, I am just going with passing the checksum as a hiera data.  Then I will evaluate with my team whether to implement the FTP or resolve the HTTP issue that I am facing right now.

**Comment by dannythk** [comment]
Able to retrieve the checksum file using checksum_url now.  But it still does not work for me because all of my checksum file has a "EOF" character at the end.  I am relatively new, how could I create a checksum file without a EOF character?  
For now, my workaround is to use checksum field instead.  But using the checksum file is ideal because I do not have to update the hieradata every time we release a new file.

**Comment by nanliu** [comment]
If there's a whitespace char, maybe a .chomp will clean it up. An example file would be helpful.

**Comment by glenjamin** [comment]
I've just run into the newline-at-EOF issue.

Would it be feasible to add a `.strip` inside the code which fetches the remote checksum?

**Comment by igalic** [comment]
+1

**Comment by dannythk** [comment]
thanks, I'll test it out to check if that fix my issue as well.

**Comment by igalic** [comment]
\o/
