### ISSUE TITLE
allow source to accept absolute file paths

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-archive#77]
I have been noticing that I constantly have to convert /tmp/some/file.txt to file:///tmp/some/file.txt and would rather just have the type code do this by munging the value. 

Any objection to adding support for the source parameter to accept absolute file paths?

**Comment by logicminds** [comment]
There is some wrapper methods in puppet that might do the job.

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util.rb#L213
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util.rb#L240

**Comment by nanliu** [comment]
Yep uri_to_path will do the job here.

**Comment by logicminds** [comment]
So the idea here would allow the type code to not only accept file urls but also absolute file paths and convert file urls to absolute file paths to be handled by the bodeco util code.   This is necessary because windows file urls do not currently convert correctly to absolute paths.   So the common format will be absolute paths but continue to support file urls to maintain backwards compatibility.

**Comment by jyaworski** [comment]
I've filed #122 to start looking at this.
