### ISSUE TITLE
file urls do not work on windows

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-archive#78]
Because windows has to be different...

The URI ruby library does not work as expected on windows because of the fact there is no root drive.  So files fail to download because the urls are interpreted incorrectly. 

Example:

```shell
irb(main):006:0> URI('file://d:/OSS/one/two/three.zip').path
=> "/OSS/one/two/three.zip"

```

And adding another slash produces another issue

```shell
irb(main):007:0> URI('file:///d:/OSS/one/two/three.zip').path
=> "/d:/OSS/one/two/three.zip"
```

This should be d:/OSS/one/two/three.zip

**Comment by logicminds** [comment]
I have this working on my own fork with the following:


```ruby
class FILE
      def initialize(_url, _options)
      end

      def normalize_path(uri)
        # URI for windows does not work as expected and returns a path without the root drive
        # this attempts to fix that
        if /^file:\/{2}([a-z,A-Z]?)/.match(uri.to_s)   # file://c:/one/two/three.zip
          uri.to_s.gsub(/^file:\/{2}([a-z,A-Z])?/, "#{$1}:")
        else
          uri.path
        end
      end
      
      def download(uri, file_path)
        src_path = normalize_path(uri)
        FileUtils.copy(src_path, file_path)
      end
    end
```

If this is acceptable I can make a PR.

**Comment by nanliu** [comment]
file:///d:/OSS/one/two/three.zip is technically correct, because I think file://d:/OSS/one/two/three.zip, would be host = d:, path = OSS, and this patch is implementing the wrong behavior (puppet:/// and not puppet:// because puppet://{server}/). So maybe implementing #77 is the better approach, because this is not intuitive for Windows.
