### ISSUE TITLE
Could not find parent provider ruby of curl 

### ISSUE THREAD

**Issue by mmarseglia** [voxpupuli/puppet-archive#87]
I'm using this module in another module and testing using TravisCI.  TravisCI is throwing the following error when testing on Puppet 4.x.  I don't know what this error means or why it only appears when testing on 4.x.

```
   Failure/Error:
       Puppet::Type.type(:archive).provide(:curl, :parent => :ruby) do
         commands :curl => 'curl'
         defaultfor :feature => :posix
       
         def download(archive_filepath)
           tempfile = Tempfile.new(tempfile_name)
           temppath = tempfile.path
           tempfile.close!
       
           @curl_params = [
     
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a '=>' expression, Could not autoload puppet/type/archive: Could not autoload puppet/provider/archive/curl: Could not find parent provider ruby of curl 
```

**Comment by nanliu** [comment]
That's a bit odd consider this module also uses travis.ci and test against Puppet 4. Do you have a link to your travis.ci test results?

**Comment by mmarseglia** [comment]
Thank you for looking.  Here is the link you requested. https://travis-ci.org/mmarseglia/puppet-jenkins/jobs/91808637

**Comment by nanliu** [comment]
Because there's no such thing as pluginsync, either the modulepath have to be aware of spec fixtures module dir, or in spec_helper make sure archive/lib is part of rubylib similar to: https://github.com/mmarseglia/puppet-jenkins/blob/fa8b05b29ca1af8e0ca45c8a11c2eef2630a0580/spec/spec_helper.rb#L6-L7

**Comment by jyaworski** [comment]
Closing due to lack of movement.

**Comment by BarnumD** [comment]
In my case, i had a similar issue come up when I was testing against a feature branch on my agent that had updated it's Puppetfile with new versions or new modules and the master branch had not had the same Puppetfile changes.
